#!/bin/bash

# this script installs RemoteGPIO v3.0 following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/HARemoteGPIO/current"

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates

packageGitHubUser="drtinaz"
packageGitHubBranch="main"


#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "HARemoteGPIO is adding entries for external Relays and Digital Inputs"
	echo "for use with relay modules controlled via Home Assistant"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing HARemoteGPIO"

	##
	## Prepare the devices in /data/RemoteGPIO/sys and conf folder
	##############################################################
	tar -xvf /data/HARemoteGPIO/FileSets/VersionIndependent/sys.tar.gz -C /data/HARemoteGPIO/
	tar -xvf /data/HARemoteGPIO/FileSets/VersionIndependent/bin.tar.gz -C /data/HARemoteGPIO/
	

	logMessage "++ $packageName installed"
fi


# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling HARemoteGPIO"

	##
	## Delete devices
	#################	
	rm -f /dev/gpio/relay_3
	rm -f /dev/gpio/relay_4
	rm -f /dev/gpio/relay_5
	rm -f /dev/gpio/relay_6
	rm -f /dev/gpio/relay_7
	rm -f /dev/gpio/relay_8
	rm -f /dev/gpio/relay_9
	rm -f /dev/gpio/relay_a
	rm -f /dev/gpio/relay_b
	rm -f /dev/gpio/relay_c
	rm -f /dev/gpio/relay_d
	rm -f /dev/gpio/relay_e
	rm -f /dev/gpio/relay_f
	rm -f /dev/gpio/relay_g
	rm -f /dev/gpio/relay_h
	rm -f /dev/gpio/relay_i
	rm -f /dev/gpio/digital_input_5
	rm -f /dev/gpio/digital_input_6
	rm -f /dev/gpio/digital_input_7
	rm -f /dev/gpio/digital_input_8
	rm -f /dev/gpio/digital_input_9
	rm -f /dev/gpio/digital_input_a
	rm -f /dev/gpio/digital_input_b
	rm -f /dev/gpio/digital_input_c
	rm -f /dev/gpio/digital_input_d
	rm -f /dev/gpio/digital_input_e
	rm -f /dev/gpio/digital_input_f
	rm -f /dev/gpio/digital_input_g
	rm -f /dev/gpio/digital_input_h
	rm -f /dev/gpio/digital_input_i
	rm -f /dev/gpio/digital_input_j
	rm -f /dev/gpio/digital_input_k
	
	
		
	logMessage "++ $packageName uninstalled"
fi


	svc -t /service/dbus-digitalinputs

logMessage "completed"
	
# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript INSTALL_FILES ADD_DBUS_SETTINGS INSTALL_SERVICES

