#!/bin/bash

# this script installs RemoteGPIO v3.0 following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/GPS-Service/current"

#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates

packageGitHubUser="drtinaz"
packageGitHubBranch="main"


#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "Installing a service to integrate router gps with venus os"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing GPS-Service"

	##
	## Prepare the devices in /data/RemoteGPIO/sys and conf folder
	##############################################################
	#tar -xvf /data/HARemoteGPIO/FileSets/VersionIndependent/sys.tar.gz -C /data/HARemoteGPIO/
	#tar -xvf /data/HARemoteGPIO/FileSets/VersionIndependent/bin.tar.gz -C /data/HARemoteGPIO/
	

	logMessage "++ $packageName installed"
fi


# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling GPS-Service"

	##
	## Delete devices
	#################	
	
	#rm -f /dev/gpio/digital_input_f

	
		
	logMessage "++ $packageName uninstalled"
fi


	#svc -t /service/dbus-digitalinputs

logMessage "completed"
	
# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript INSTALL_SERVICES INSTALL_FILES

